// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: derrors/v1/error.view.proto

package derrorsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorView is the lightweight public JSON payload for HTTP responses.
// Field names + json_name ensure snake_case in protojson output to match error.view.schema.json.
type ErrorView struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Core
	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`       // required by schema
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // optional
	Reason  string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`   // optional
	// Correlation & tracing (snake_case for JSON)
	Correlation string `protobuf:"bytes,10,opt,name=correlation,proto3" json:"correlation,omitempty"`
	TraceId     string `protobuf:"bytes,11,opt,name=trace_id,proto3" json:"trace_id,omitempty"`
	SpanId      string `protobuf:"bytes,12,opt,name=span_id,proto3" json:"span_id,omitempty"`
	// Retry hint (seconds); corresponds to schema's retry_after_seconds
	RetryAfterSeconds int32 `protobuf:"varint,20,opt,name=retry_after_seconds,proto3" json:"retry_after_seconds,omitempty"`
	// Human-facing links (docs/support/etc.)
	Links []*Link `protobuf:"bytes,30,rep,name=links,proto3" json:"links,omitempty"`
	// Validation violations (aka "fields" in the schema)
	Fields        []*Violation `protobuf:"bytes,40,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorView) Reset() {
	*x = ErrorView{}
	mi := &file_derrors_v1_error_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorView) ProtoMessage() {}

func (x *ErrorView) ProtoReflect() protoreflect.Message {
	mi := &file_derrors_v1_error_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorView.ProtoReflect.Descriptor instead.
func (*ErrorView) Descriptor() ([]byte, []int) {
	return file_derrors_v1_error_view_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorView) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorView) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorView) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ErrorView) GetCorrelation() string {
	if x != nil {
		return x.Correlation
	}
	return ""
}

func (x *ErrorView) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ErrorView) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *ErrorView) GetRetryAfterSeconds() int32 {
	if x != nil {
		return x.RetryAfterSeconds
	}
	return 0
}

func (x *ErrorView) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *ErrorView) GetFields() []*Violation {
	if x != nil {
		return x.Fields
	}
	return nil
}

var File_derrors_v1_error_view_proto protoreflect.FileDescriptor

const file_derrors_v1_error_view_proto_rawDesc = "" +
	"\n" +
	"\x1bderrors/v1/error.view.proto\x12\n" +
	"derrors.v1\x1a\x16derrors/v1/error.proto\"\xb2\x02\n" +
	"\tErrorView\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12 \n" +
	"\vcorrelation\x18\n" +
	" \x01(\tR\vcorrelation\x12\x1a\n" +
	"\btrace_id\x18\v \x01(\tR\btrace_id\x12\x18\n" +
	"\aspan_id\x18\f \x01(\tR\aspan_id\x120\n" +
	"\x13retry_after_seconds\x18\x14 \x01(\x05R\x13retry_after_seconds\x12&\n" +
	"\x05links\x18\x1e \x03(\v2\x10.derrors.v1.LinkR\x05links\x12-\n" +
	"\x06fields\x18( \x03(\v2\x15.derrors.v1.ViolationR\x06fieldsB$Z\"dirpx.dev/api/derrors/v1;derrorsv1b\x06proto3"

var (
	file_derrors_v1_error_view_proto_rawDescOnce sync.Once
	file_derrors_v1_error_view_proto_rawDescData []byte
)

func file_derrors_v1_error_view_proto_rawDescGZIP() []byte {
	file_derrors_v1_error_view_proto_rawDescOnce.Do(func() {
		file_derrors_v1_error_view_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_derrors_v1_error_view_proto_rawDesc), len(file_derrors_v1_error_view_proto_rawDesc)))
	})
	return file_derrors_v1_error_view_proto_rawDescData
}

var file_derrors_v1_error_view_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_derrors_v1_error_view_proto_goTypes = []any{
	(*ErrorView)(nil), // 0: derrors.v1.ErrorView
	(*Link)(nil),      // 1: derrors.v1.Link
	(*Violation)(nil), // 2: derrors.v1.Violation
}
var file_derrors_v1_error_view_proto_depIdxs = []int32{
	1, // 0: derrors.v1.ErrorView.links:type_name -> derrors.v1.Link
	2, // 1: derrors.v1.ErrorView.fields:type_name -> derrors.v1.Violation
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_derrors_v1_error_view_proto_init() }
func file_derrors_v1_error_view_proto_init() {
	if File_derrors_v1_error_view_proto != nil {
		return
	}
	file_derrors_v1_error_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_derrors_v1_error_view_proto_rawDesc), len(file_derrors_v1_error_view_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_derrors_v1_error_view_proto_goTypes,
		DependencyIndexes: file_derrors_v1_error_view_proto_depIdxs,
		MessageInfos:      file_derrors_v1_error_view_proto_msgTypes,
	}.Build()
	File_derrors_v1_error_view_proto = out.File
	file_derrors_v1_error_view_proto_goTypes = nil
	file_derrors_v1_error_view_proto_depIdxs = nil
}
