// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: derrors/v1/error.proto

package derrorsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tag is a simple key/value pair for flat, text-only annotations.
// This message intentionally supports only strings to keep it portable
// across logs, traces, and message buses without extra encoding.
type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`     // Tag name, e.g. "component" or "owner".
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // Tag value, e.g. "storage" or "team-a".
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_derrors_v1_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_derrors_v1_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_derrors_v1_error_proto_rawDescGZIP(), []int{0}
}

func (x *Tag) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Tag) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Link describes a human-facing resource related to the error,
// such as documentation, support, or terms.
type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rel           string                 `protobuf:"bytes,1,opt,name=rel,proto3" json:"rel,omitempty"`     // Relation/type of the link: "doc", "support", "more", "terms", etc.
	Href          string                 `protobuf:"bytes,2,opt,name=href,proto3" json:"href,omitempty"`   // Absolute or service-relative URL.
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"` // Optional human-readable title/caption for UI.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_derrors_v1_error_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_derrors_v1_error_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_derrors_v1_error_proto_rawDescGZIP(), []int{1}
}

func (x *Link) GetRel() string {
	if x != nil {
		return x.Rel
	}
	return ""
}

func (x *Link) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

func (x *Link) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

// Violation captures a single input/validation error on a concrete field.
// Suitable for 4xx responses where you want to show multiple problems at once.
type Violation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`     // Path to the field, e.g. "spec.replicas".
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`   // Machine-friendly reason code, e.g. "must_be_greater_than_or_equal_to_1".
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // Human-readable explanation.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Violation) Reset() {
	*x = Violation{}
	mi := &file_derrors_v1_error_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Violation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Violation) ProtoMessage() {}

func (x *Violation) ProtoReflect() protoreflect.Message {
	mi := &file_derrors_v1_error_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Violation.ProtoReflect.Descriptor instead.
func (*Violation) Descriptor() ([]byte, []int) {
	return file_derrors_v1_error_proto_rawDescGZIP(), []int{2}
}

func (x *Violation) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Violation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Violation) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// QuotaInfo conveys current quota/limit state relevant to the error.
// This helps clients decide whether to retry later or reduce usage.
type QuotaInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`                              // Quota/limit name, e.g. "requests_per_minute".
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                                   // Total allowed in the window.
	Remaining     int64                  `protobuf:"varint,3,opt,name=remaining,proto3" json:"remaining,omitempty"`                           // Remaining within the current window.
	ResetSeconds  int64                  `protobuf:"varint,4,opt,name=reset_seconds,json=resetSeconds,proto3" json:"reset_seconds,omitempty"` // Seconds until the window resets.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuotaInfo) Reset() {
	*x = QuotaInfo{}
	mi := &file_derrors_v1_error_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaInfo) ProtoMessage() {}

func (x *QuotaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_derrors_v1_error_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaInfo.ProtoReflect.Descriptor instead.
func (*QuotaInfo) Descriptor() ([]byte, []int) {
	return file_derrors_v1_error_proto_rawDescGZIP(), []int{3}
}

func (x *QuotaInfo) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *QuotaInfo) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QuotaInfo) GetRemaining() int64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *QuotaInfo) GetResetSeconds() int64 {
	if x != nil {
		return x.ResetSeconds
	}
	return 0
}

// RetryInfo gives client-side guidance on whether and when to retry.
type RetryInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Retryable         bool                   `protobuf:"varint,1,opt,name=retryable,proto3" json:"retryable,omitempty"`                                            // true if the server considers this error retryable.
	RetryAfterSeconds int64                  `protobuf:"varint,2,opt,name=retry_after_seconds,json=retryAfterSeconds,proto3" json:"retry_after_seconds,omitempty"` // If > 0, client should wait at least this long.
	Policy            string                 `protobuf:"bytes,3,opt,name=policy,proto3" json:"policy,omitempty"`                                                   // Optional hint: "exponential", "fixed", etc.
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RetryInfo) Reset() {
	*x = RetryInfo{}
	mi := &file_derrors_v1_error_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryInfo) ProtoMessage() {}

func (x *RetryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_derrors_v1_error_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryInfo.ProtoReflect.Descriptor instead.
func (*RetryInfo) Descriptor() ([]byte, []int) {
	return file_derrors_v1_error_proto_rawDescGZIP(), []int{4}
}

func (x *RetryInfo) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *RetryInfo) GetRetryAfterSeconds() int64 {
	if x != nil {
		return x.RetryAfterSeconds
	}
	return 0
}

func (x *RetryInfo) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

// Cause is a minimal element of the error cause chain. It allows
// the server to expose a shallow, safe description of underlying problems
// without dumping full internal errors.
type Cause struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`       // Short identifier, e.g. "io_timeout", "sql_error".
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Brief description of the underlying cause.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cause) Reset() {
	*x = Cause{}
	mi := &file_derrors_v1_error_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cause) ProtoMessage() {}

func (x *Cause) ProtoReflect() protoreflect.Message {
	mi := &file_derrors_v1_error_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cause.ProtoReflect.Descriptor instead.
func (*Cause) Descriptor() ([]byte, []int) {
	return file_derrors_v1_error_proto_rawDescGZIP(), []int{5}
}

func (x *Cause) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Cause) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Environment describes the runtime environment in which the error occurred.
// This is useful for multi-region, multi-service deployments and for
// correlating errors across components.
type Environment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`         // Logical service name.
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`         // Service version/release.
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`           // Region name, e.g. "us-central1".
	Zone          string                 `protobuf:"bytes,4,opt,name=zone,proto3" json:"zone,omitempty"`               // Zone/availability zone, e.g. "us-central1-b".
	Instance      string                 `protobuf:"bytes,5,opt,name=instance,proto3" json:"instance,omitempty"`       // Instance/pod/node identifier.
	Environment   string                 `protobuf:"bytes,6,opt,name=environment,proto3" json:"environment,omitempty"` // Deployment environment: "prod", "staging", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Environment) Reset() {
	*x = Environment{}
	mi := &file_derrors_v1_error_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Environment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Environment) ProtoMessage() {}

func (x *Environment) ProtoReflect() protoreflect.Message {
	mi := &file_derrors_v1_error_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Environment.ProtoReflect.Descriptor instead.
func (*Environment) Descriptor() ([]byte, []int) {
	return file_derrors_v1_error_proto_rawDescGZIP(), []int{6}
}

func (x *Environment) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Environment) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Environment) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Environment) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *Environment) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *Environment) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

// ErrorDescriptor is a portable, self-contained error envelope.
// It is designed to be embedded into gRPC status details, logged, or
// sent over a message bus.
//
// This is a stable external contract, not the internal derrors.Error.
// All fields are intentionally simple so they can be handled by different
// languages and transports.
type ErrorDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Logical/business plane.
	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`       // High-level error code, e.g. "unavailable", "invalid".
	Reason  string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`   // Optional dotted, fine-grained reason, e.g. "storage.pg.connect_timeout".
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // Short client-safe message (may match ErrorView.message).
	// Transport projections.
	HttpStatus int32 `protobuf:"varint,10,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"` // Resolved HTTP status, e.g. 503, 400.
	GrpcCode   int32 `protobuf:"varint,11,opt,name=grpc_code,json=grpcCode,proto3" json:"grpc_code,omitempty"`       // Resolved gRPC status (as integer), e.g. 14 for UNAVAILABLE.
	// Diagnostics and correlation.
	CorrelationId string `protobuf:"bytes,20,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"` // Client/server correlation or idempotency key.
	TraceId       string `protobuf:"bytes,21,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`                   // Distributed trace identifier, if available.
	SpanId        string `protobuf:"bytes,22,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`                      // Span identifier within the trace.
	// Client guidance.
	Retry *RetryInfo `protobuf:"bytes,30,opt,name=retry,proto3" json:"retry,omitempty"` // Retry/backoff hints.
	Quota *QuotaInfo `protobuf:"bytes,31,opt,name=quota,proto3" json:"quota,omitempty"` // Quota/limit state relevant to this error.
	// Structured input/validation errors (typically for 4xx).
	Violations []*Violation `protobuf:"bytes,40,rep,name=violations,proto3" json:"violations,omitempty"`
	// Human-facing navigation to docs/support/etc.
	Links []*Link `protobuf:"bytes,50,rep,name=links,proto3" json:"links,omitempty"`
	// Shallow cause chain; deeper/internal errors should stay in logs/traces.
	Causes []*Cause `protobuf:"bytes,60,rep,name=causes,proto3" json:"causes,omitempty"`
	// Deployment/runtime context in which the error was produced.
	Env *Environment `protobuf:"bytes,70,opt,name=env,proto3" json:"env,omitempty"`
	// Flat annotations for extra safe-to-expose metadata.
	Tags          []*Tag `protobuf:"bytes,80,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDescriptor) Reset() {
	*x = ErrorDescriptor{}
	mi := &file_derrors_v1_error_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDescriptor) ProtoMessage() {}

func (x *ErrorDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_derrors_v1_error_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDescriptor.ProtoReflect.Descriptor instead.
func (*ErrorDescriptor) Descriptor() ([]byte, []int) {
	return file_derrors_v1_error_proto_rawDescGZIP(), []int{7}
}

func (x *ErrorDescriptor) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorDescriptor) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ErrorDescriptor) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDescriptor) GetHttpStatus() int32 {
	if x != nil {
		return x.HttpStatus
	}
	return 0
}

func (x *ErrorDescriptor) GetGrpcCode() int32 {
	if x != nil {
		return x.GrpcCode
	}
	return 0
}

func (x *ErrorDescriptor) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ErrorDescriptor) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ErrorDescriptor) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *ErrorDescriptor) GetRetry() *RetryInfo {
	if x != nil {
		return x.Retry
	}
	return nil
}

func (x *ErrorDescriptor) GetQuota() *QuotaInfo {
	if x != nil {
		return x.Quota
	}
	return nil
}

func (x *ErrorDescriptor) GetViolations() []*Violation {
	if x != nil {
		return x.Violations
	}
	return nil
}

func (x *ErrorDescriptor) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *ErrorDescriptor) GetCauses() []*Cause {
	if x != nil {
		return x.Causes
	}
	return nil
}

func (x *ErrorDescriptor) GetEnv() *Environment {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ErrorDescriptor) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_derrors_v1_error_proto protoreflect.FileDescriptor

const file_derrors_v1_error_proto_rawDesc = "" +
	"\n" +
	"\x16derrors/v1/error.proto\x12\n" +
	"derrors.v1\"-\n" +
	"\x03Tag\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"B\n" +
	"\x04Link\x12\x10\n" +
	"\x03rel\x18\x01 \x01(\tR\x03rel\x12\x12\n" +
	"\x04href\x18\x02 \x01(\tR\x04href\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\"S\n" +
	"\tViolation\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x80\x01\n" +
	"\tQuotaInfo\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x1c\n" +
	"\tremaining\x18\x03 \x01(\x03R\tremaining\x12#\n" +
	"\rreset_seconds\x18\x04 \x01(\x03R\fresetSeconds\"q\n" +
	"\tRetryInfo\x12\x1c\n" +
	"\tretryable\x18\x01 \x01(\bR\tretryable\x12.\n" +
	"\x13retry_after_seconds\x18\x02 \x01(\x03R\x11retryAfterSeconds\x12\x16\n" +
	"\x06policy\x18\x03 \x01(\tR\x06policy\"5\n" +
	"\x05Cause\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xab\x01\n" +
	"\vEnvironment\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x12\n" +
	"\x04zone\x18\x04 \x01(\tR\x04zone\x12\x1a\n" +
	"\binstance\x18\x05 \x01(\tR\binstance\x12 \n" +
	"\venvironment\x18\x06 \x01(\tR\venvironment\"\xa4\x04\n" +
	"\x0fErrorDescriptor\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1f\n" +
	"\vhttp_status\x18\n" +
	" \x01(\x05R\n" +
	"httpStatus\x12\x1b\n" +
	"\tgrpc_code\x18\v \x01(\x05R\bgrpcCode\x12%\n" +
	"\x0ecorrelation_id\x18\x14 \x01(\tR\rcorrelationId\x12\x19\n" +
	"\btrace_id\x18\x15 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x16 \x01(\tR\x06spanId\x12+\n" +
	"\x05retry\x18\x1e \x01(\v2\x15.derrors.v1.RetryInfoR\x05retry\x12+\n" +
	"\x05quota\x18\x1f \x01(\v2\x15.derrors.v1.QuotaInfoR\x05quota\x125\n" +
	"\n" +
	"violations\x18( \x03(\v2\x15.derrors.v1.ViolationR\n" +
	"violations\x12&\n" +
	"\x05links\x182 \x03(\v2\x10.derrors.v1.LinkR\x05links\x12)\n" +
	"\x06causes\x18< \x03(\v2\x11.derrors.v1.CauseR\x06causes\x12)\n" +
	"\x03env\x18F \x01(\v2\x17.derrors.v1.EnvironmentR\x03env\x12#\n" +
	"\x04tags\x18P \x03(\v2\x0f.derrors.v1.TagR\x04tagsB$Z\"dirpx.dev/api/derrors/v1;derrorsv1b\x06proto3"

var (
	file_derrors_v1_error_proto_rawDescOnce sync.Once
	file_derrors_v1_error_proto_rawDescData []byte
)

func file_derrors_v1_error_proto_rawDescGZIP() []byte {
	file_derrors_v1_error_proto_rawDescOnce.Do(func() {
		file_derrors_v1_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_derrors_v1_error_proto_rawDesc), len(file_derrors_v1_error_proto_rawDesc)))
	})
	return file_derrors_v1_error_proto_rawDescData
}

var file_derrors_v1_error_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_derrors_v1_error_proto_goTypes = []any{
	(*Tag)(nil),             // 0: derrors.v1.Tag
	(*Link)(nil),            // 1: derrors.v1.Link
	(*Violation)(nil),       // 2: derrors.v1.Violation
	(*QuotaInfo)(nil),       // 3: derrors.v1.QuotaInfo
	(*RetryInfo)(nil),       // 4: derrors.v1.RetryInfo
	(*Cause)(nil),           // 5: derrors.v1.Cause
	(*Environment)(nil),     // 6: derrors.v1.Environment
	(*ErrorDescriptor)(nil), // 7: derrors.v1.ErrorDescriptor
}
var file_derrors_v1_error_proto_depIdxs = []int32{
	4, // 0: derrors.v1.ErrorDescriptor.retry:type_name -> derrors.v1.RetryInfo
	3, // 1: derrors.v1.ErrorDescriptor.quota:type_name -> derrors.v1.QuotaInfo
	2, // 2: derrors.v1.ErrorDescriptor.violations:type_name -> derrors.v1.Violation
	1, // 3: derrors.v1.ErrorDescriptor.links:type_name -> derrors.v1.Link
	5, // 4: derrors.v1.ErrorDescriptor.causes:type_name -> derrors.v1.Cause
	6, // 5: derrors.v1.ErrorDescriptor.env:type_name -> derrors.v1.Environment
	0, // 6: derrors.v1.ErrorDescriptor.tags:type_name -> derrors.v1.Tag
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_derrors_v1_error_proto_init() }
func file_derrors_v1_error_proto_init() {
	if File_derrors_v1_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_derrors_v1_error_proto_rawDesc), len(file_derrors_v1_error_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_derrors_v1_error_proto_goTypes,
		DependencyIndexes: file_derrors_v1_error_proto_depIdxs,
		MessageInfos:      file_derrors_v1_error_proto_msgTypes,
	}.Build()
	File_derrors_v1_error_proto = out.File
	file_derrors_v1_error_proto_goTypes = nil
	file_derrors_v1_error_proto_depIdxs = nil
}
